import noimgprofile from "./no-profile.jpg";
import ImgMenu from "./Menu.svg";
import plus from "./Plus.svg";
import seting from "./Settings.svg";
import contact from "./Contacts.svg";
import call from "./call.svg";
import save from "./save.svg";
import invite from "./Invite friends.svg";
import FAQ from "./FAQ.svg";
import menuprofile from "./Profile menu.svg";
import back from "./back.svg";
import chat from "./Chat.svg";
import union from "./Union.png";
import lock from "./lock.svg";
import data from "./data.svg";
import device from "./Device.svg";
import imgprev1 from "./Rectangle 38.svg";
import imgprev2 from "./Rectangle 39.svg";
import imgprev3 from "./Rectangle 40.svg";
import imgprev4 from "./Rectangle 41.svg";
import imgprev5 from "./Rectangle 42.svg";
import imgprev6 from "./Rectangle 44.svg";
import imgprev7 from "./Rectangle 45.svg";

export { noimgprofile, ImgMenu, plus, seting, contact, call, save, invite, FAQ, menuprofile, back, chat, imgprev1, imgprev2, imgprev3, imgprev4, imgprev5, imgprev6, imgprev7, union, lock, data, device };
